# render.yaml

services:
  - type: web
    name: meal-planner-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.enableCORS false
